### ISSUE TITLE
Looking for contact

### ISSUE THREAD

**Issue by cesrenji** [Black5ugar/SDN-ddos#1]
Hello author, I am from China and I borrowed your project but something happened afterwards which is private. I hope you can give me a contact information. Email or something and I will tell you the details

**Comment by cesrenji** [comment]
This is particularly important to me and I would like you to give me a contact

**Comment by black5ugar** [comment]
I'm sorry, but this was just a casual assignment that I wrote a long time ago and I have forgotten the knowledge inside. So I can't provide you with any further help.
Also, the system and software versions that were used at that time are already very old. If any issues arise now, it's not surprising.
