### ISSUE TITLE
again

### ISSUE THREAD

**Issue by cesrenji** [Black5ugar/SDN-ddos#2]
Hello author, it's me again. The main reason I requested your contact information last week is that my graduation design was selected by my supervisor and she intends to take my graduation design to the competition. However, I am well aware that a large part, if not all, of my graduation design is based on your project. One of the main reasons for seeking your contact information is to ask for your permission. Let me enter the competition with a design that has elements of your project

**Comment by black5ugar** [comment]
Of course you can use my project and do whatever you want.
For privacy reasons, I am unwilling to provide my personal contact information. If it necessary, my Github homepage will suffice.
